runtime: nodejs16

instance_class: F2

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /static
    static_dir: build/static
